# Generated by Django 3.1.2 on 2020-11-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('registered_date', models.DateTimeField(verbose_name='date registered')),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
