# Generated by Django 3.1.2 on 2020-11-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='registered_date',
        ),
    ]
