# Generated by Django 3.1.3 on 2020-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_remove_person_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
